-- Add OSHA-required fields to incidents table
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS employee_name TEXT;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS job_title_at_time TEXT;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS date_of_injury DATE;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS injury_description TEXT;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS body_part_affected TEXT;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS injury_type TEXT;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS days_away INT DEFAULT 0;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS days_restricted INT DEFAULT 0;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS death BOOLEAN DEFAULT FALSE;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS treated_in_er BOOLEAN DEFAULT FALSE;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS hospitalized BOOLEAN DEFAULT FALSE;
